### ISSUE TITLE
async-to-gen conflicts with babel

### ISSUE THREAD

**Issue by Morriz** [leebyron/async-to-gen#15]
I believe it is in everybody's best interest to join these efforts with the babel plugin. Their ecosystem is widely used and this module only makes problems for babel users.

If anybody wants to just run babel's plugin-async-to-generator, they can do so. If anybody has a problem with getting it to work, contact the authors about a documentation problem. Please don't go rogue on us and start making conflicting modules that don't play nice with require.extensions philosophy.

#11 and #12 are related to this.

**Comment by leebyron** [comment]
If you need other features of Babel, then you should just use Babel. It has a plugin for supporting async functions.

If you do not need other features of Babel other than support of async functions, then you should use this library. It will perform faster, is simpler, and has cleaner output if you need to distribute the translated code.

**Comment by Morriz** [comment]
I have read the docs, which say the same. You are not answering the above concerns tho.

**Comment by leebyron** [comment]
Could you elaborate on the concerns? I'm not sure what you're proposing be done

**Comment by Morriz** [comment]
I think I have to let go of my hope: that we join forces when the same result is sought.

**Comment by leebyron** [comment]
I'm honestly confused here. I'm happy to take constructive feedback about how this tool or its documentation could be improved, but it is unclear to me what it is that you're suggesting be done or what you mean by joining forces. 

Babel is an awesome tool. You should use it if it solves problems that you have. I use it all the time in my own projects. Babel even has support for async functions! 

However just because Babel support exists doesn't mean no other tools should. This tool, async-to-gen, makes intentionally different choices from Babel about how it works. That does not make it objectively better or worse, it just presents an alternative which under some circumstances may be a better fit and under others may be worse. 

If you need other features of Babel, like JSX or ES7+, then you should definitely use Babel! It's what I would and do choose for that circumstance. If you're using Babel then you already have config files set up and adding async support is not hard. But if you don't need anything else Babel supports then this tool may be the better choice for you!

Does that mean it conflicts or makes problems for Babel? Or that this module is somehow "rogue" or not playing nice with some philosophy? I wouldn't think so. It's just another available option should it be the right one for your project. 

If you do think it is problematic and have clearer feedback about how to improve that, then I would be more than happy to hear it and attempt to improve the tool.

**Comment by Morriz** [comment]
Thanks for the elaboration. We agree on mostly all of it. One problem tho, as stated before: it does not work with babel runtime. I am using another lib called zeit/micro, that uses your lib as is, and breaks my app that relies on babel runtime...so your little piece of code is breaking other code that relies on it, when used in conjunction with babel...not good

**Comment by hzoo** [comment]
> I am using another lib called zeit/micro, that uses your lib as is, and breaks my app that relies on babel runtime

Ok I don't think that part was explained as clearly in the first posts. So the issue sounds like another 3rd party lib (https://github.com/zeit/micro) in this case is using async-to-gen but your own code is using babel and it's not working together?

**Comment by leebyron** [comment]
Aha, I understand now, thanks. It seems like the right path forward is for zeit/micro to provide an opt-out of using this library's register for those who are using Babel register already, since as you pointed out, only one node register hook can be used at a time.

I see you've already opened an issue on that library, so hopefully progress can be made there

**Comment by Morriz** [comment]
Yes. I already managed to work around the shortcoming. Thanks for thinking along :)

**Comment by leebyron** [comment]
Just FYI - I added a change in #16 that I'll be releasing on npm shortly that should allow use of `async-node` alongside `babel/register` without clobbering, however you'll still need to configure babel to be aware of the async function syntax.

This will probably fix the issue you reported at https://github.com/zeit/micro/issues/89 - though I haven't actually tested it within that library.

**Comment by Morriz** [comment]
Wow, great work :)
