### ISSUE TITLE
iife and crockford-iife functions break

### ISSUE THREAD

**Issue by fundon** [leebyron/async-to-gen#25]
Examples:

```js
// iife
(async () => {

  await test()

})()
```

```js
// crockford-iife
(async () => {

  await test()

}())
```

**Comment by leebyron** [comment]
Could you provide more info about what you expect to happen and what you see instead?

When I run your first example in `async-node`

```js
// iife
(async () => {
  await test()
})()
```

I get the correct output of a Promise.

Your second example is not legal syntax for the same reason that the following is not legal syntax:

```js
(() => {
  test()
}())
```

Crockford style iifes only work with function literals, not arrow functions, and async functions work in this style as well in `async-node`. This example returns a Promise:

```js
(async function () {
  test()
}())
```

**Comment by leebyron** [comment]
Added these two IIFE to the test cases to illustrate that they transform as expected

**Comment by fundon** [comment]
Below case breaks:

```js
const test = {
  async run () {
  }
}

(async () => {
  await test.run()
})()
```

error:

```
iife.js:6
(() => __async(function*(){
^

TypeError: (intermediate value) is not a function
```

**Comment by leebyron** [comment]
That error is expected given that code (though node could be more helpful with its errors).

You can test this by trying the same thing using node without the async/await (not using this library at all):

```js
const test = {
  run () {
  }
}

(() => {
  test.run()
})()
```

```
iife.js:6
(() => {
^

TypeError: (intermediate value) is not a function
```

This is because of Automatic Semicolon Insertion (a good resource: https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch5.md#automatic-semicolons)

This is because any expression followed by `()` assumes that you mean the previous expression is a function to be called. In this case: `const test = {run(){}}(()=>{test.run()})` JavaScript thinks `test` will be assigned the result of a function call where `{run(){}}` is the function to call and `()=>{test.run()}` is the argument to the function.

Check out https://astexplorer.net/#/efPw48Ufoh to see how JavaScript parses this.

The fix is to ensure there's a semicolon somewhere before your IIFE.

**Comment by fundon** [comment]
Thank you for your explain.
