### ISSUE TITLE
Comparison with fast-async?

### ISSUE THREAD

**Issue by sedubois** [leebyron/async-to-gen#35]
I just wondered how this compares against https://github.com/MatAtBread/fast-async in terms of performance, etc?

**Comment by leebyron** [comment]
`fast-async` itself is a babel plugin, so the performance of transform will be considerably slower since async-to-gen uses a much simpler transform than Babel (of course, Babel has way more features).

However if you look into how `fast-async` works, it's really just a wrapper around [`nodent`](https://github.com/MatAtBread/nodent) which I hadn't heard of before and is really interesting in that it unrolls async functions directly into promise chains.

The pro of that approach is that it removes the internal generator iterator, which likely is where they see the performance boost and that means it either supports a broader set of target platforms or they don't need a follow-up transform like regenerator to do so. The relative downside is that the code it outputs is pretty different from what's written (but sourcemaps can help with that).

I haven't yet gotten nodent to actually work on a test codebase before so I can't speak to runtime performance - but let me know if you do some tests.

**Comment by leebyron** [comment]
Closing this issue - but feel free to keep up discussion
